name: Flutter Portfolio  # Change the name here

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Use the latest version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Use v2 as the latest version
        with:
          flutter-version: '3.16.5'  # Specify the Flutter version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # Install Firebase CLI globally

      - name: Install dependencies
        run: flutter pub get
        working-directory: portfolio  # Set working directory to your project folder

      - name: Build Flutter Web App
        run: flutter build web
        working-directory: portfolio  # Set working directory to your project folder

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Ensure the Firebase token is set
        working-directory: portfolio  # Set working directory to your project folder
